spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1q2w3e4r1!
    url: jdbc:mysql://localhost:3306/rate_limit
#  data:
#    redis:
#      host: redis://localhost
#      port: 6379
